version: '3'

services:
  app:
    image: php-strictus/strictus
    container_name: strictus
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/src/app
